### PR TITLE
commons-math3 dependency and migrating imagej-ops Mesh data structure

### PR DESCRIPTION
**Pull request by kephale**

### CODE REVIEW

**Comment by kephale** [comment]
@rimadoma and @tibuch any issues with this PR? @tibuch this starts the move of your Mesh structure over to this repo, and we'll need to update imagej-ops to depend on imagej-mesh at some point to eliminate the duplication.

**Comment by ctrueden** [comment]
What's with all these merges? Could you please run `git fetch origin; git rebase origin/master` on this branch locally, then `git push --force` afterwards?

> we'll need to update imagej-ops to depend on imagej-mesh at some point to eliminate the duplication.

Happy to do that as soon as this repository is far enough along to have a 0.1.0 release! Just let me know, and I'll cut the release, add the dependency to imagej-ops, and remove the old duplicate classes from the ops sources.

**Comment by kephale** [comment]
None of those had an effect. 

`git fetch origin; git rebase origin/master  
Current branch master is up to date.`

`git push --force  
Everything up-to-date`

I don't know what the merge PRs are, but I do this stuff through the github web interface by clicking the "Merge pull request" button, which I believe adds those lines.

**Comment by ctrueden** [comment]
You are working on your own `master` branch, which you pushed to `kephale/master` but not to `origin/master` (i.e., `imagej/master`). Here is a git graph illustrating the current discrepancies:
```
$ git log --date-order --graph --decorate --oneline master origin/master kephale/master
*   9345b4f (kephale/master) Merge pull request #4 from kephale/migrating-imagej-ops-mesh
|\
| * 02b32d8 Migrating imagej-ops Mesh data structure to imagej-mesh
|/
*   8acfd89 Merge pull request #3 from kephale/switch-commons-math3
|\
| * a11c645 commons-math3 dependency and Vec3 to Vector3D conversion
* |   da065ee Merge pull request #2 from kephale/fixing-artifact-id
|\ \
| |/
|/|
| * 848f711 Fixing artifact ID
|/
*   1e61e66 Merge pull request #1 from kephale/cleaning-package-hierarchy
|\
| * 1a0e63a Changing package hierarchy to net.imagej.mesh
|/
* 70fe616 (HEAD -> master, origin/master, origin/HEAD) Add STL format
* b767b9f Initial project skeleton
```
So what happened is: you filed a few PRs in `kephale/imagej-mesh` and then merged them... and now you are filing a PR from `kephale/master` to `imagej/master`, which contains all the previous merges and more. This makes some sense, but I found it pretty confusing. Simpler would be to simply file PRs against `imagej/imagej-mesh` one by one.

I am going to just update `imagej/master` here to match `kephale/master`—i.e.: do a fast-forward merge.

**Comment by ctrueden** [comment]
You can probably just delete your fork now, and work on topic branches here in `imagej/imagej-mesh` directly. If you want feedback on a branch, file it as a PR. Otherwise, you can just merge it to master and push directly, since you are the primary maintainer. Whatever you prefer.

**Comment by kephale** [comment]
Ok cool, thank you! Yes, topic branches were what I was hoping to do, but I just wanted to split out each feature branch as soon as you brought up the issue, as it was a particularly good time to do so.

Happy New Year, Curtis!!!

**Pull request merged**
